### ISSUE TITLE
最近剛開始用，提示都是“ban ip“

### ISSUE THREAD

**Issue by kshuzhiwang** [HSSLC/manhuagui-dlr#1]
最近剛開始用，提示都是“ban ip“，持續了有3天左右。
使用chrome是可以在線看漫畫的，不知道作者最近是否可以正常使用模塊？

**Comment by HSSLC** [comment]
我都還可以正常使用，可以檢查一下是否有設定proxy，有的話試著關掉
因為我程式還沒支援proxy，在系統設定開啟proxy時會無法連線

**Comment by kshuzhiwang** [comment]
由于我網路特殊，必須時刻開啟系統的proxy，如果是這樣的話，那我先試試別的
十分感謝作者你的回答

**Comment by kshuzhiwang** [comment]
有沒有別的模塊可以結合使用，走proxy？

**Comment by HSSLC** [comment]
那我這幾天改進一下好了，加入proxy功能

**Comment by HSSLC** [comment]
proxy功能已經加入，可以測試看看
首次需要手動設定
