### ISSUE TITLE
PIL 無法開啟 webp 類型的檔案

### ISSUE THREAD

**Issue by lanesu** [HSSLC/manhuagui-dlr#2]
有成功下載第一個 webp 檔案，接下來就出現錯誤訊息：

UnidentifiedImageError: cannot identify image file '1_seemh-001-563b.jpg.webp'

請問是不是我的環境漏裝了什麼套件呢？
謝謝！

**Comment by HSSLC** [comment]
可能是Pillow模組或該張webp有問題
可以提供一下該部作品ID與執行
```
from PIL import features
print(features.check_module('webp'))
```
的輸出結果嗎？
在這段時間也可以試試看更新或重裝Pillow
更新：`pip install --upgrade Pillow`
重裝：`pip install --ignore-installed Pillow`
也確認一下該張webp可以成功被其他軟體(瀏覽器)開啟

**Comment by lanesu** [comment]
我試了 ID 4288 和 18847 的作品，都是下載一張圖片就跳出無法辨識檔案類型的錯誤訊息。
到 raw 資料夾裡面可以用瀏覽器開啟 webp 檔案，內容也是對的。

執行 check_module 那兩行的結果是 False。

重裝 Pillow 就可以正常下載了，看訊息重裝的是 Pillow 8.0.x 版，
我到資料夾裡面看昨天安裝的是 7.0.0 版，應該是比較舊的版本沒辦法辨識 webp 檔案吧！
很謝謝你！
