### ISSUE TITLE
3705获取不到

### ISSUE THREAD

**Issue by Z-fly** [HSSLC/manhuagui-dlr#3]
![image](https://user-images.githubusercontent.com/10470892/173239458-29c6683e-61ce-4b5b-9b33-35a1f9b4ff57.png)

**Comment by HSSLC** [comment]
這個問題已經在 b8bcd889f567999fd1f2e687b610264d96c2dc01 （2020/9/7）中被修正，
經測試3705在最新版本中正常運作，請嘗試下載最新版本。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/173241063-08872a0e-644a-46f3-80bf-9d384759104a.png)
奇怪了

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/173268273-83284679-0057-497a-8411-a0718cc8dd02.png)
我发现问题所在了

**Comment by Z-fly** [comment]
域名用www的就行了

**Comment by HSSLC** [comment]
有可能是該網站對不同分流的反應有所不同，程式中預設使用tw是為了取得繁體標題，之後將改進註解如何調整分流。
