### ISSUE TITLE
non-ASCII character may cause too long filename

### ISSUE THREAD

**Issue by Plectranthus-fg** [HSSLC/manhuagui-dlr#5]
non-ASCII code may cause some problem and safity issue to the file system.
I will accept pr and comment that line later.
but I'll write a prompt to user that thay can decide to unquote filename or not.

_Originally posted by @HSSLC in https://github.com/HSSLC/manhuagui-dlr/issues/4#issuecomment-1312335673_

**Comment by Plectranthus-fg** [comment]
One charater in cjk with url encoding will capture 9 charaters in filename, which will easily cause too long filename error.
Filename should be cut if too long.

**Comment by HSSLC** [comment]
Finally I choose to unquote URI filename(#4) and add filename cutting function.
