### ISSUE TITLE
下載14話漫畫后被封ip

### ISSUE THREAD

**Issue by jinbasex** [HSSLC/manhuagui-dlr#7]
因爲今天需要遠行昨夜下載了14話漫畫 早上起來 發現進不去漫畫櫃
換個ip就正常
煩請大神指教一二，有什麽辦法解決ip被封嗎？

**Comment by HSSLC** [comment]
可以嘗試把下載圖片間隔期間調長一點，才比較不會因為瀏覽太快而被封鎖
被封的期間就只能換一個ip使用，過幾天通常會自然解封

**Comment by jinbasex** [comment]
好的 我去試試 謝謝您的回復
